# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('data_aula', models.DateField(default='01 de janeiro de 2000', null=True)),
                ('descricao_aula', models.CharField(max_length=200)),
                ('aula_agendada', models.BooleanField(default=True)),
                ('aula_concluida', models.BooleanField(default=True)),
                ('periodo_aula', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AulaIngrediente',
            fields=[
                ('id_aula_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_projetada_aula', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantidade_utilizada_aula', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ingrediente', models.CharField(max_length=200)),
                ('quantidade_calorica_ingrediente', models.DecimalField(decimal_places=1, max_digits=6)),
                ('aproveitamento_ingrediente', models.DecimalField(decimal_places=1, max_digits=4)),
                ('quantidade_estoque_ingrediente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantidade_reservada_ingrediente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_ingrediente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo_retirada_estoque', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aulaingrediente',
            name='id_ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.Ingrediente'),
        ),
        migrations.AddField(
            model_name='aula',
            name='ingredientes',
            field=models.ManyToManyField(through='aula.AulaIngrediente', to='aula.Ingrediente'),
        ),
    ]
